import {generate_array, shuffle_array, set_innerHTML} from "./utils.js";

let setup = document.getElementById('setup')
setup.onsubmit = async (event) => {
    event.preventDefault()
    const num_teams = setup.num_teams.value
    const mode = setup.mode.value
    const card_set = setup.card_set.value
    game_init(num_teams, mode, card_set)
}

// Constants and Enumerations -----------------------------------------------
const PERSON = 0; const WORLD  = 1; const OBJECT = 2; const ACTION = 3; const NATURE = 4; const RANDOM = 5;

const SHORT = 30;
const LONG = 60;


// Card Sets -----------------------------------------------------------------

const person_words =shuffle_array( [
    "Jesus Christ",
    "Julius Caesar",
    "Alexander the Great",
    "William the Conqueror",
    "Napoleon Bonaparte",
    "Queen Victoria",
    "Queen Elizabeth II",
    "King Henry VIII",
    "King Charles III",
    "Neville Chamberlain",
    "Winston Churchill",
    "Clement Attlee",
    "Margaret Thatcher",
    "Tony Blair",
    "Gordon Brown",
    "David Cameron",
    "Theresa May",
    "Boris Johnson",
    "Keir Starmer",
    "Adolf Hitler",
    "Joseph Stalin",
    "George Washington",
    "Alexander Hamilton",
    "Abraham Lincoln",
    "Woodrow Wilson",
    "Franklin D. Roosevelt",
    "Harry S. Truman",
    "Richard Nixon",
    "Ronald Reagan",
    "Bill Clinton",
    "George W. Bush",
    "Barack Obama",
    "Donald Trump",
    "Joe Biden",
    "Hillary Clinton",
    "Cleopatra",
    "Benito Mussolini",
    "Harry Potter",
    "Hermione Granger",
    "Ron Weasley",
    "Albus Dumbledore",
    "Severus Snape",
    "Voldermort",
    "Padme Amidala",
    "Obi-Wan Kenobi",
    "Han Solo",
    "Luke Skywalker",
    "Yoda",
    "Darth Vader",
    "R2-D2",
    "Darth Maul",
    "Chewbacca",
    "Leia Organa",
    "Emperor Palpatine",
    "C-3PO",
    "General Grievous",
    "Boba Fett",
    "Jabba The Hutt",
    "Mace Windu",
    "Count Dooku",
    "Qui-Gon Jinn",
    "Spider-Man",
    "Wolverine",
    "Thor Odinson",
    "Iron Man",
    "Hulk",
    "Captain America",
    "Hawkeye",
    "Charles Xavier",
    "Doctor Strange",
    "Black Panther",
    "Black Widow",
    "The Winter Soldier",
    "Magneto",
    "Batman",
    "Superman",
    "The Flash",
    "Wonder Woman",
    "Albert Einstein",
    "Isaac Newton",
    "Pythagoras",
    "Plato",
    "Aristotle",
    "Archimedes",
    "Zeus",
    "Elon Musk",
    "Mark Zuckerberg",
    "Gordon Ramsey",
    "Cristiano Ronaldo",
    "Lionel Messi",
    "Erling Haaland",
    "Bukayo Saka",
    "Jude Bellingham",
    "Jamie Carragher",
    "Gary Neville",
    "Roy Keane",
    "Thierry Henry",
    "Mohammed Salah",
    "David Beckham",
    "Diego Maradona",
    "Gareth Southgate",
    "Pele",
    "Tom Hardy",
    "Jake Gyllenhaal",
    "Daniel Day-Lewis",
    "Bryan Cranston",
    "Gary Oldman",
    "Christian Bale",
    "Denzel Washington",
    "Leonardo DiCaprio",
    "Cillian Murphy",
    "Kevin Spacey",
    "Willem Dafoe",
    "Chadwick Boseman",
    "Liam Neeson",
    "Kevin Bacon",
    "Hugh Jackman",
    "Bradley Cooper",
    "Adam Driver",
    "Robert Downey Jr.",
    "Benedict Cumberbatch",
    "Ryan Gosling",
    "Ewan McGregor",
    "Andy Serkis",
    "Ian McDiarmid\n",
    "Alan Rickman",
    "Will Smith",
    "Jason Momoa",
    "Chris Hemsworth",
    "Idris Elba",
    "Jason Statham",
    "Chris Evans",
    "Hugh Laurie",
    "James Earl Jones",
    "Pierce Brosnan",
    "Russell Crowe",
    "Daniel Craig",
    "Matt Smith",
    "Bruce Lee",
    "Jackie Chan",
    "Mao Zi Dong",
    "Michael Caine",
    "Anthony Hopkins",
    "Mads Mikkelsen",
    "John Krasinski",
    "Eddie Redmayne",
    "Henry Cavill",
    "Brad Pitt",
    "Bob Odenkirk",
    "Michael Keaton",
    "Robert Patterson",
    "Colin Firth",
    "Joaquin Phoenix",
    "The Joker",
    "Bane",
    "The Mad Hatter",
    "Heath Ledger",
    "Sydney Sweeney",
    "Ana De Armas",
    "Zendaya",
    "Sabrina Carpenter",
    "Megan Fox",
    "Scarlett Johansson",
    "Ryan Reynolds",
    "Blake Lively",
    "Jennifer Lawrence",
    "Margot Robbie",
    "Natalie Portman",
    "Angelina Jolie",
    "Jennifer Lopez",
    "Tom Cruise",
    "Johnny Depp",
    "Julia Roberts",
    "Louis Theroux",
    "Mariah Carey",
    "Adele",
    "Taylor Swift",
    "Aretha Franklin",
    "Lady Gaga",
    "Beyonce",
    "Elvis Presley",
    "Michael Jackson",
    "Whitney Houston",
    "Billie Eilish",
    "Katy Perry",
    "Stevie Wonder",
    "Prince",
    "John Lennon",
    "Nicki Minaj",
    "Frank Sinatra",
    "Marvin Gaye",
    "Tina Turner",
    "Dolly Parton",
    "Chris Brown",
    "Harry Styles",
    "David Bowie",
    "Rihanna",
    "Elton John",
    "ABBA",
    "AC/DC",
    "The Beatles",
    "The Bee Gees",
    "Coldplay",
    "Led Zeppelin",
    "Nirvana",
    "One Direction",
    "Queen",
    "Radiohead",
    "Red Hot Chili Peppers",
    "The Smiths",
    "Spice Girls",
    "U2",
    "Steve Jobs",
    "Bill Gates",
    "Bill Nye the Science Guy",
    "Master Chief",
    "Chuck Norris",
    "Kanye West",
    "Mr Beast",
    "Osama Bin Laden",
    "Usain Bolt",
    "LeBron James",
    "Michael Jordan",
    "Tom Brady",
    "Loki Laufyson",
    "Patrick Stewart",
    "George Clooney",
    "Jay-Z",
    "Princess Diana",
    "Diana Ross",
    "Calvin Harris",
    "Florence Welch"
] );
const  world_words =shuffle_array( ["Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "The Bahamas",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Brazil",
    "Bulgaria",
    "Cabo Verde (Cape Verde)",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Costa Rica",
    "Ivory Coast",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Estonia",
    "Eswatini (Swaziland)",
    "Ethiopia",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "Gambia",
    "Gaza Strip",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Greenland",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "North Korea",
    "South Korea,",
    "Kosovo",
    "Kuwai",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Madagascar",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (Burma)",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palistine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "South Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Virgin Islands",
    "Uruguay",
    "Uzbekistan",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "West Bank",
    "Yemen",
    "London",
    "Reading",
    "Bristol",
    "Worthing",
    "Brighton",
    "Sheffield",
    "Liverpool",
    "Manchester",
    "Birmingham",
    "Leicester",
    "York",
    "Bradford",
    "Southampton",
    "Portsmouth",
    "Coventry",
    "Cardiff",
    "Swansea",
    "Oxford",
    "Cambridge",
    "Exeter",
    "Aberdeen",
    "Glasgow",
    "Edinburgh",
    "Bath",
    "City of London (London Not Enough)",
    "Abu Dhabi",
    "Amsterdam",
    "Athens",
    "Baghdad",
    "Bangkok",
    "Beijing",
    "Shanghai",
    "Beirut",
    "Berlin",
    "Strasbourg",
    "Munich",
    "Cape Town",
    "Brasília",
    "Sao Paulo",
    "Rio de Janeiro",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Cairo",
    "Alexandria",
    "Canberra",
    "Melbourne",
    "Sydney",
    "Copenhagen",
    "Dublin",
    "Galway",
    "Gibraltar",
    "Havana",
    "Islamabad",
    "Jakarta",
    "Jerusalem",
    "Kingston",
    "Kyiv",
    "Lisbon",
    "Porto",
    "Madrid",
    "Barcelona",
    "Catalonia",
    "Valencia",
    "Bilbao",
    "Marbella",
    "Girona",
    "Santander",
    "Ibiza",
    "Mexico City",
    "Moscow",
    "Leningrad",
    "Stalingrad",
    "Siberia",
    "New Delhi",
    "Oslo",
    "Mumbai",
    "Paris",
    "Normandy",
    "Brittany",
    "Marseille",
    "Lyon",
    "Bordeaux",
    "Nice",
    "Prague",
    "Pyongyang",
    "Riga",
    "Riyadh",
    "Reykjavík",
    "Rome",
    "Milan",
    "Turin",
    "Florence",
    "Bologna",
    "Venice",
    "Naples",
    "Genoa",
    "Pisa",
    "Verona",
    "Seoul",
    "Sofia",
    "Stockholm",
    "Taipei",
    "Tehran",
    "Tokyo",
    "Kyoto",
    "Hiroshima",
    "Nagasaki",
    "Vienna",
    "Warsaw",
    "Auschwitz",
    "Washington, D.C.",
    "Austin",
    "San Francisco",
    "New York City",
    "Seattle",
    "Chicago",
    "Denver",
    "Boston",
    "Los Angeles",
    "New Orleans",
    "San Diego",
    "Houston",
    "Phoenix",
    "Las Vegas",
    "Detroit",
    "Albuquerque",
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Mississippi",
    "Nevada",
    "New Jersey",
    "New Mexico",
    "North Carolina",
    "New York",
    "Ohio",
    "Texas",
    "Washington",
    "West Virginia",
    "Statue of Liberty",
    "Leaning Tower of Pisa",
    "Eiffel Tower",
    "Big Ben",
    "Colosseum",
    "Empire State Building",
    "London Eye",
    "Golden Gate Bridge",
    "St. Peter's Basilica",
    "Notre Dame",
    "Great Wall of China",
    "Arc de Triomphe",
    "Sydney Opera House",
    "Berlin Wall",
    "Stonehenge",
    "Mount Kilimanjaro ",
    "The Great Sphinx",
    "Tower Bridge",
    "Taj Mahal",
    "The Forbidden City",
    "Pyramids of Giza",
    "Mount Everest",
    "Capitol Hill",
    "Brooklyn Bridge",
    "Louvre Museum",
    "Times Square ",
    "Buckingham Palace",
    "The White House\n",
    "Versailles",
    "Machu Picchu",
    "Pompeii",
    "Christ the Redeemer",
    "Burj Khalifa",
    "Tower of London",
    "Niagara Falls",
    "The Grand Canyon",
    "St. Paul's Cathedral",
    "Windsor Castle",
    "Mount Rushmore",
    "Central Park",
    "Mount Fuji",
    "Westminster Abbey ",
    "Alcatraz Prison",
    "White Cliffs of Dover",
    "The Gherkin",
    "Washington Monument",
    "Pentagon",
    "Mount Vesuvius",
    "Victoria Falls",
    "Petra",
    "Yellowstone National Park",
    "Hagia Sophia",
    "Wailing Wall",
    "Loch Ness",
    "Mecca",
    "Sydney Harbor Bridge",
    "Sistine Chapel",
    "Brighton Pier",
    "Hollywood Walk of Fame",
    "Ellis Island",
    "British Museum",
    "Piccadilly Circus",
    "Kremlin",
    "Trafalgar Square",
    "Brooklyn"] );
const object_words =shuffle_array( ["record",
    "leg",
    "bait",
    "hook",
    "invention",
    "spade",
    "sleet",
    "ink",
    "dust",
    "metal",
    "friend",
    "crayon",
    "pump",
    "train",
    "arm",
    "kitty",
    "coat",
    "rail",
    "boy",
    "teeth",
    "loaf",
    "crow",
    "ice",
    "hose",
    "flock",
    "wax",
    "station",
    "point",
    "eye",
    "mailbox",
    "hole",
    "pie",
    "expert",
    "lace",
    "stitch",
    "spark",
    "income",
    "nation",
    "waves",
    "tin",
    "airplane",
    "end",
    "cover",
    "nest",
    "playground",
    "iron",
    "time",
    "tooth",
    "knot",
    "representative",
    "plantation",
    "geese",
    "stomach",
    "stream",
    "wood",
    "spot",
    "wool",
    "cave",
    "glass",
    "coil",
    "birthday",
    "scissors",
    "view",
    "discovery",
    "dogs",
    "store",
    "icicle",
    "trucks",
    "bag",
    "lunchroom",
    "thing",
    "furniture",
    "finger",
    "grandmother",
    "design",
    "weight",
    "chess",
    "vein",
    "account",
    "lamp",
    "society",
    "cattle",
    "curve",
    "robin",
    "dinner",
    "eyes",
    "rake",
    "street",
    "button",
    "cracker",
    "can",
    "parcel",
    "church",
    "achiever",
    "man",
    "woman",
    "surprise",
    "food",
    "part",
    "air",
    "competition",
    "level",
    "board",
    "oven",
    "honey",
    "men",
    "stick",
    "attack",
    "change",
    "mine",
    "health",
    "jar",
    "cap",
    "agreement",
    "seed",
    "corn",
    "peace",
    "writer",
    "face",
    "exchange",
    "fowl",
    "sea",
    "baseball",
    "receipt",
    "haircut",
    "increase",
    "actor",
    "ants",
    "earth",
    "range",
    "root",
    "milk",
    "offer",
    "hands",
    "door",
    "humor",
    "breath",
    "work",
    "mountain",
    "head",
    "boat",
    "push",
    "calendar",
    "soda",
    "crib",
    "blade",
    "bucket",
    "arch",
    "pocket",
    "arithmetic",
    "sign",
    "winter",
    "start",
    "skirt",
    "box",
    "position",
    "tramp",
    "thumb",
    "scale",
    "railway",
    "angle",
    "sugar",
    "toes",
    "riddle",
    "payment",
    "pot",
    "beginner",
    "screw",
    "jelly",
    "rabbit",
    "fall",
    "structure",
    "birth",
    "match",
    "creator",
    "lunch",
    "wound",
    "support",
    "waste",
    "money",
    "rose",
    "crate",
    "doll",
    "example",
    "moon",
    "school",
    "monkey",
    "voyage",
    "credit",
    "thunder",
    "respect",
    "curtain",
    "calculator",
    "self",
    "property",
    "spy",
    "chance",
    "table",
    "quicksand",
    "bead",
    "thrill",
    "window",
    "song",
    "rock",
    "trains",
    "pail",
    "decision",
    "territory",
    "shape",
    "sky",
    "unit",
    "dog",
    "jewel",
    "title",
    "tongue",
    "hair",
    "yarn",
    "name",
    "grain",
    "ball",
    "base",
    "snails",
    "crown",
    "trade",
    "flesh",
    "watch",
    "loss",
    "chicken",
    "daughter",
    "advertisement",
    "pleasure",
    "order",
    "act",
    "market",
    "yam",
    "cup",
    "play",
    "pizzas",
    "bed",
    "stretch",
    "recess",
    "stone",
    "division",
    "fear",
    "branch",
    "jeans",
    "bird",
    "deer",
    "measure",
    "reward",
    "drawer",
    "snake",
    "powder",
    "hobbies",
    "vessel",
    "purpose",
    "quiver",
    "leather",
    "wealth",
    "harmony",
    "fold",
    "snail",
    "bear",
    "appliance",
    "stranger",
    "silk",
    "paper",
    "wall",
    "language",
    "group",
    "distribution",
    "servant",
    "rule"] );
const action_words =shuffle_array( [
    "Accepting",
    "Adding",
    "Admiring",
    "Admitting",
    "Advising",
    "Agreeing",
    "Allowing",
    "Announcing",
    "Appearing",
    "Applying",
    "Appreciating",
    "Approving",
    "Arguing",
    "Arriving",
    "Asking",
    "Assuming",
    "Attacking",
    "Avoiding",
    "Baking",
    "Balancing",
    "Banning",
    "Bathing",
    "Being",
    "Beating",
    "Becoming",
    "Beginning",
    "Believing",
    "Belonging",
    "Bending",
    "Betting",
    "Binding",
    "Biting",
    "Blowing",
    "Breaking",
    "Bringing",
    "Building",
    "Burning",
    "Buying",
    "Calling",
    "Calming",
    "Canceling",
    "Carrying",
    "Catching",
    "Changing",
    "Choosing",
    "Cleaning",
    "Climbing",
    "Closing",
    "Collecting",
    "Coming",
    "Committing",
    "Comparing",
    "Competing",
    "Complaining",
    "Completing",
    "Concentrating",
    "Concerning",
    "Confirming",
    "Connecting",
    "Considering",
    "Consisting",
    "Consulting",
    "Continuing",
    "Contributing",
    "Controlling",
    "Cooking",
    "Copying",
    "Correcting",
    "Counting",
    "Creating",
    "Crossing",
    "Crying",
    "Cutting",
    "Dancing",
    "Dealing",
    "Deciding",
    "Decreasing",
    "Defending",
    "Defining",
    "Delivering",
    "Denying",
    "Depending",
    "Describing",
    "Designing",
    "Destroying",
    "Developing",
    "Dying",
    "Digging",
    "Disagreeing",
    "Disappearing",
    "Discovering",
    "Discussing",
    "Disliking",
    "Dividing",
    "Doing",
    "Doubting",
    "Dragging",
    "Drawing",
    "Dreaming",
    "Dressing",
    "Drinking",
    "Driving",
    "Dropping",
    "Drying",
    "Eating",
    "Educating",
    "Encouraging",
    "Ending",
    "Enjoying",
    "Entering",
    "Escaping",
    "Establishing",
    "Examining",
    "Existing",
    "Expecting",
    "Explaining",
    "Exploring",
    "Expressing",
    "Extending",
    "Failing",
    "Falling",
    "Feeding",
    "Feeling",
    "Fighting",
    "Finding",
    "Finishing",
    "Fitting",
    "Fixing",
    "Flying",
    "Focusing",
    "Following",
    "Forcing",
    "Forgetting",
    "Forgiving",
    "Freezing",
    "Frying",
    "Getting",
    "Giving",
    "Going",
    "Growing",
    "Guessing",
    "Happening",
    "Hating",
    "Having",
    "Hearing",
    "Helping",
    "Hiding",
    "Hitting",
    "Holding",
    "Hoping",
    "Hugging",
    "Hurrying",
    "Identifying",
    "Ignoring",
    "Imagining",
    "Improving",
    "Including",
    "Increasing",
    "Informing",
    "Insisting",
    "Introducing",
    "Inviting",
    "Joining",
    "Jumping",
    "Keeping",
    "Kicking",
    "Killing",
    "Kissing",
    "Knocking",
    "Knowing",
    "Laughing",
    "Laying",
    "Leading",
    "Learning",
    "Leaving",
    "Lending",
    "Letting",
    "Lying",
    "Lifting",
    "Lighting",
    "Liking",
    "Listening",
    "Living",
    "Looking",
    "Losing",
    "Loving",
    "Making",
    "Managing",
    "Marking",
    "Mattering",
    "Meaning",
    "Measuring",
    "Meeting",
    "Mentioning",
    "Missing",
    "Moving",
    "Needing",
    "Noticing",
    "Offering",
    "Opening",
    "Operating",
    "Ordering",
    "Organizing",
    "Owning",
    "Painting",
    "Parking",
    "Participating",
    "Passing",
    "Paying",
    "Performing",
    "Planning",
    "Playing",
    "Pointing",
    "Possessing",
    "Posting",
    "Pouring",
    "Practicing",
    "Preferring",
    "Preparing",
    "Presenting",
    "Pressing",
    "Preventing",
    "Printing",
    "Producing",
    "Promising",
    "Protecting",
    "Proving",
    "Providing",
    "Pulling",
    "Punching",
    "Pushing",
    "Putting",
    "Qualifying",
    "Questioning",
    "Quitting",
    "Raining",
    "Raising",
    "Reaching",
    "Reading",
    "Realizing",
    "Receiving",
    "Recognizing",
    "Recording",
    "Reducing",
    "Referring",
    "Reflecting",
    "Refusing",
    "Regretting",
    "Relating",
    "Relaxing",
    "Releasing",
    "Relying",
    "Remembering",
    "Removing",
    "Repairing",
    "Repeating",
    "Replacing",
    "Replying",
    "Reporting",
    "Representing",
    "Requesting",
    "Requiring",
    "Resting",
    "Returning",
    "Revealing",
    "Riding",
    "Ringing",
    "Rising",
    "Risking",
    "Rolling",
    "Running",
    "Saving",
    "Saying",
    "Seeing",
    "Selling",
    "Sending",
    "Serving",
    "Setting",
    "Shaking",
    "Sharing",
    "Shooting",
    "Showing",
    "Shutting",
    "Singing",
    "Sitting",
    "Sleeping",
    "Smelling",
    "Smiling",
    "Solving",
    "Speaking",
    "Spending",
    "Standing",
    "Starting",
    "Staying",
    "Stealing",
    "Sticking",
    "Stopping",
    "Studying",
    "Succeeding",
    "Suffering"
] );
const nature_words =shuffle_array( ["vegetable",
    "artichoke",
    "asparagus",
    "broccoli",
    "brussels sprouts",
    "cabbage",
    "cauliflower",
    "celery",
    "coriander",
    "eggplant",
    "fennel",
    "arugula",
    "bok choy",
    "collard greens",
    "kale",
    "lettuce",
    "mustard",
    "spinach",
    "beans",
    "bean sprouts",
    "black beans",
    "broad beans",
    "chickpeas",
    "green beans",
    "kidney beans",
    "lentils",
    "peanuts",
    "pinto beans",
    "runner beans",
    "soy beans",
    "peas",
    "mushroom",
    "nettles",
    "onion",
    "chives",
    "garlic",
    "leek",
    "shallot",
    "spring onion UK",
    "bell pepper",
    "chili",
    "jalapeño",
    "habanero",
    "paprika",
    "tabasco",
    "cayenne pepper",
    "rhubarb",
    "beetroot",
    "carrot",
    "ginger",
    "parsnip",
    "radish",
    "wasabi",
    "horseradish",
    "turnip",
    "potato",
    "sweet potato",
    "sweetcorn",
    "melon",
    "butternut squash",
    "banana",
    "courgette",
    "cucumber",
    "watercress",
    "animal",
    "",",",
    "Aardvark",
    "Alaskan Husky",
    "Albatross",
    "Alligator",
    "Alpaca",
    "Anaconda",
    "Anchovies",
    "Ant",
    "Anteater",
    "Antelope",
    "Ape",
    "Armadillo",
    "Axolotl",
    "Baboon",
    "Badger",
    "Bald Eagle",
    "Barn Owl",
    "Bat",
    "Bear",
    "Bearded Dragon",
    "Beaver",
    "Bee",
    "Beetle",
    "Bird",
    "Bison",
    "Blue Tit",
    "Blue Whale",
    "Brown Bear",
    "Butterfly",
    "Camel",
    "Capybara",
    "Carp",
    "Cat",
    "Caterpillar",
    "Catfish",
    "Chameleon",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Cobra",
    "Cocker Spaniel",
    "Cockroach",
    "Cougar",
    "Cow",
    "Coyote",
    "Crab",
    "Cricket",
    "Crocodile",
    "Crow",
    "Dachshund",
    "Dalmatian",
    "Deer",
    "Dire Wolf",
    "Dog",
    "Dolphin",
    "Donkey",
    "Dragonfly",
    "Duck",
    "Eagle",
    "Earthworm",
    "Eel",
    "Elephant",
    "Emu",
    "Falcon",
    "Ferret",
    "Firefly",
    "Fish",
    "Flea",
    "Fly",
    "Fox",
    "Frog",
    "Fruit Fly",
    "Gazelle",
    "Gerbil",
    "German Shepherd",
    "Giraffe",
    "Goat",
    "Golden Retriever",
    "Goldfish",
    "Goose",
    "Gopher",
    "Gorilla",
    "Grasshopper",
    "Greyhound",
    "Grizzly Bear",
    "Guinea Pig",
    "Hamster",
    "Hare",
    "Hawk",
    "Hippopotamus",
    "Honey Badger",
    "Hornet",
    "Horse",
    "Human",
    "Husky",
    "Hyena",
    "Iguana",
    "Insect",
    "Jackal",
    "Jaguar",
    "Jellyfish",
    "Kangaroo",
    "King Penguin",
    "Koala",
    "Koi Fish",
    "Komodo Dragon",
    "Labradoodle",
    "Labrador",
    "Ladybug",
    "Leech",
    "Lemur",
    "Leopard",
    "Liger",
    "Lion",
    "Lizard",
    "Llama",
    "Lobster",
    "Locust",
    "Lynx",
    "Maggot",
    "Magpie",
    "Manatee",
    "Meerkat",
    "Megalodon",
    "Microraptor",
    "Mockingbird",
    "Mole",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mosquito",
    "Moth",
    "Mouse",
    "Mule",
    "Newt",
    "Ocelot",
    "Octopus",
    "Orangutan",
    "Ostrich",
    "Otter",
    "Owl",
    "Ox",
    "Oyster",
    "Parrot",
    "Peacock",
    "Penguin",
    "Pheasant",
    "Phoenix",
    "Pig",
    "Pigeon",
    "Piranha",
    "Pit Bull",
    "Platypus",
    "Polar Bear",
    "Poodle",
    "Porcupine",
    "Possum",
    "Prawn",
    "Pterodactyl",
    "Pufferfish",
    "Puffin",
    "Pug",
    "Puma",
    "Python",
    "Quail",
    "Rabbit",
    "Raccoon",
    "Rat",
    "Rattlesnake",
    "Red Squirrel",
    "Reindeer",
    "Robin",
    "Scallops",
    "Scorpion",
    "Sea Bass",
    "Seagull",
    "Seahorse",
    "Seal",
    "Shark",
    "Sheep",
    "Skunk",
    "Sloth",
    "Slug",
    "Snail",
    "Snake",
    "Snow Leopard",
    "Sparrow",
    "Sperm Whale",
    "Spider",
    "Squid",
    "Squirrel",
    "Starfish",
    "Stick Insect",
    "Stingray",
    "Stork",
    "Swan",
    "Swordfish",
    "Tarantula",
    "Tasmanian Devil",
    "Termite",
    "Tick",
    "Tiger",
    "Tortoise",
    "Trout",
    "Tuna",
    "Turkey",
    "Turtle",
    "Tyrannosaurus Rex",
    "Velociraptor",
    "Venus Flytrap",
    "Viper",
    "Vulture",
    "Walrus",
    "Warthog",
    "Wasp",
    "Weasel",
    "White Shark",
    "White Tiger",
    "Wild Boar",
    "Wolf",
    "Woodpecker",
    "Woolly Mammoth",
    "Worm",
    "Yeti",
    "Zebra",
    "plant",
    "chlorophyll",
    "astronomy",
    "astrophysics",
    "atom",
    "cell",
    "climate",
    "chemical",
    "fossil",
    "gravity",
    "genetics",
    "molecule",
    "mineral",
    "organism",
    "particle",
    "weather"] );
const random_words =shuffle_array( [
    "literature",
    "nerve",
    "rifle",
    "lineage",
    "exact",
    "pavement",
    "impulse",
    "attraction",
    "herb",
    "spite",
    "rib",
    "ethnic",
    "tumour",
    "orgy",
    "headquarters",
    "obscure",
    "mastermind",
    "reliance",
    "spectrum",
    "detective",
    "waste",
    "mourning",
    "animal",
    "eye",
    "forestry",
    "exhibition",
    "superintendent",
    "energy",
    "fresh",
    "contrast",
    "depression",
    "employ",
    "size",
    "hunting",
    "rob",
    "put",
    "discourage",
    "intelligence",
    "pass",
    "commerce",
    "slip",
    "confuse",
    "fibre",
    "cabin",
    "incentive",
    "squash",
    "stake",
    "flock",
    "circumstance",
    "upset",
    "inhabitant",
    "observer",
    "field",
    "overall",
    "fold",
    "innocent",
    "station",
    "take",
    "syndrome",
    "fox",
    "long",
    "dark",
    "brick",
    "ambiguous",
    "climb",
    "will",
    "exile",
    "sock",
    "pill",
    "temporary",
    "breed",
    "confrontation",
    "king",
    "hostage",
    "diameter",
    "hide",
    "mystery",
    "train",
    "note",
    "card",
    "horn",
    "tourist",
    "race",
    "fog",
    "basket",
    "decline",
    "build",
    "loot",
    "mask",
    "recover",
    "suspicion",
    "elbow",
    "chair",
    "torch",
    "sharp",
    "clarify",
    "thirsty",
    "guide",
    "profession",
    "spokesperson",
    "voice",
    "tropical",
    "battery",
    "paralyzed",
    "rabbit",
    "spring",
    "court",
    "neglect",
    "ambition",
    "area",
    "write",
    "soup",
    "coma",
    "prosper",
    "wonder",
    "memorial",
    "disco",
    "admire",
    "fly",
    "rotation",
    "flexible",
    "vegetarian",
    "speculate",
    "basis",
    "claim",
    "groan",
    "spray",
    "accumulation",
    "foster",
    "forum",
    "taste",
    "pool",
    "recommend",
    "platform",
    "jury",
    "pair",
    "temptation",
    "ground",
    "lid",
    "combination",
    "dip",
    "cow",
    "arise",
    "referee",
    "is",
    "fat",
    "illusion",
    "pride",
    "inject",
    "harmony",
    "bathtub",
    "orange",
    "comprehensive",
    "calendar",
    "differ",
    "say",
    "content",
    "thigh",
    "Venus",
    "matrix",
    "occupy",
    "question",
    "opponent",
    "estimate",
    "preparation",
    "motorcycle",
    "norm",
    "bless",
    "beer",
    "grip",
    "elaborate",
    "enter",
    "director",
    "surgeon",
    "threaten",
    "determine",
    "myth",
    "exceed",
    "conglomerate",
    "pat",
    "revolution",
    "nominate",
    "belong",
    "absence",
    "practical",
    "scenario",
    "stable",
    "save",
    "rebellion",
    "excuse",
    "aspect",
    "cunning",
    "install",
    "plead",
    "acceptable",
    "degree",
    "dependence",
    "class",
    "treaty",
    "raid",
    "staircase",
    "monarch",
    "routine",
    "graphic",
    "acute",
    "track",
    "yard",
    "similar",
    "deposit",
    "silver",
    "scene",
    "creed",
    "integration",
    "baby",
    "sandwich",
    "owner",
    "amber",
    "twitch",
    "bean",
    "round",
    "float",
    "length",
    "mutation",
    "linen",
    "dialogue",
    "dare",
    "equation",
    "annual",
    "finger",
    "chain",
    "understand",
    "clearance",
    "summary",
    "dictate",
    "hesitate",
    "seller",
    "activate",
    "cruel",
    "clean",
    "cellar",
    "few",
    "turn",
    "sell",
    "drift",
    "provide",
    "climate",
    "mug",
    "cycle",
    "intensify",
    "cold",
    "dozen",
    "remunerate",
    "arrangement",
    "produce",
    "trench",
    "progress",
    "proclaim",
    "salon",
    "an",
    "extract",
    "gear",
    "attractive",
    "summer",
    "solve",
    "crevice",
    "oil",
    "boat",
    "ask",
    "damage",
    "employee",
    "compound",
    "sermon",
    "stamp",
    "car",
    "measure",
    "acquaintance",
    "favourite",
    "proof",
    "load",
    "pause",
    "place",
    "overcharge",
    "prize",
    "condition",
    "hang",
    "gesture",
    "volume",
    "fee",
    "conservation",
    "pigeon",
    "pile",
    "cooperation",
    "willpower",
    "pen",
    "widen",
    "pleasure",
    "column",
    "edge",
    "unfair",
    "basic",
    "treat",
    "major",
    "printer",
    "reasonable",
    "civilian",
    "gallon",
    "effective",
    "dough",
    "cream",
    "victory",
    "offset",
    "exclude",
    "pepper",
    "election",
    "craft",
    "ally",
    "clothes",
    "god",
    "stride",
    "cassette",
    "false",
    "diplomatic",
    "retire",
    "discreet",
    "copyright",
    "warm",
    "noise",
    "champion",
    "bus",
    "nuance",
    "prayer",
    "kinship",
    "pasture",
    "hike",
    "argument",
    "girlfriend",
    "us",
    "ancestor",
    "owl",
    "farewell",
    "episode",
    "dine",
    "reality",
    "photocopy",
    "social",
    "composer",
    "emotion",
    "surround",
    "variant",
    "gravel",
    "laundry",
    "survivor",
    "behavior",
    "ticket",
    "wake",
    "disaster",
    "fail",
    "confidence",
    "challenge",
    "management",
    "acid",
    "revoke",
    "answer",
    "dump",
    "agreement",
    "history",
    "exploit",
    "at",
    "distance",
    "participate",
    "unique",
    "tidy",
    "constitutional",
    "addition",
    "monkey",
    "missile",
    "consensus",
    "wagon",
    "defend",
    "see",
    "misery",
    "sigma",
    "hypotenuse",
    "league",
    "charisma",
    "goon",
    "replica",
    "saint",
    "curse",
    "tomb",
    "balloon",
    "football",
    "rugby",
    "golf",
    "aura",
    "gold",
    "lithium",
    "construct"
] );

// Game Setup and Logic ------------------------------------------------------

/**
 *
 * @param {int} num_teams Number of teams in the game [Min 2, Max 100]
 * @param {string} mode Timer Setting:
 *
 *      `"default"` = 30s
 *      `"long"`    = 60s
 *      `"free"`    = No Timer
 *
 * @param {string} card_set Source of words for the game:
 *
 *      `"default"` = Preset word lists - "./assets/*.json"
 *      `"ai"`      = Generate words by querying LLM *NOT YET IMPLEMENTED*
 */
function game_init(num_teams, mode, card_set){
    switch(card_set){
        case "default":
            switch(mode){
                case "default":
                    start_timed_game(num_teams,SHORT);
                    break;
                case "long":
                    start_timed_game(num_teams, LONG);
                    break;
                case "free":
                    start_free_game(num_teams);
                    break;
                default:
                    console.log("Invalid mode: ", mode);
            }
            break
        case "ai":
            console.log("Not Yet Implemented");
            break;
        default:
            console.log("Something went wrong, card set.");
            break;
    }
}


async function start_timed_game(num_teams, timer_length){
    let current_team = 0;
    let game_over = false;
    let team_points = generate_array(num_teams, 0);

    await set_innerHTML("../pages/cat_select.html")
    document.getElementById("cat_select").onsubmit = async (event) => {
        event.preventDefault();
        console.log(event.submitter.id)

    }

}

function start_free_game(numTeams){
    console.log("Not Yet Implemented.")
}

