/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedLobbyCreateRouteImport } from './routes/_authed/lobby/create'
import { Route as AuthedLobbyLobbyIdRouteImport } from './routes/_authed/lobby/$lobbyId'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLobbyCreateRoute = AuthedLobbyCreateRouteImport.update({
  id: '/lobby/create',
  path: '/lobby/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLobbyLobbyIdRoute = AuthedLobbyLobbyIdRouteImport.update({
  id: '/lobby/$lobbyId',
  path: '/lobby/$lobbyId',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/home': typeof AuthedHomeRoute
  '/lobby/$lobbyId': typeof AuthedLobbyLobbyIdRoute
  '/lobby/create': typeof AuthedLobbyCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/home': typeof AuthedHomeRoute
  '/lobby/$lobbyId': typeof AuthedLobbyLobbyIdRoute
  '/lobby/create': typeof AuthedLobbyCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/lobby/$lobbyId': typeof AuthedLobbyLobbyIdRoute
  '/_authed/lobby/create': typeof AuthedLobbyCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/rules'
    | '/home'
    | '/lobby/$lobbyId'
    | '/lobby/create'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rules'
    | '/home'
    | '/lobby/$lobbyId'
    | '/lobby/create'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/rules'
    | '/_authed/home'
    | '/_authed/lobby/$lobbyId'
    | '/_authed/lobby/create'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RulesRoute: typeof RulesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/lobby/create': {
      id: '/_authed/lobby/create'
      path: '/lobby/create'
      fullPath: '/lobby/create'
      preLoaderRoute: typeof AuthedLobbyCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/lobby/$lobbyId': {
      id: '/_authed/lobby/$lobbyId'
      path: '/lobby/$lobbyId'
      fullPath: '/lobby/$lobbyId'
      preLoaderRoute: typeof AuthedLobbyLobbyIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedLobbyLobbyIdRoute: typeof AuthedLobbyLobbyIdRoute
  AuthedLobbyCreateRoute: typeof AuthedLobbyCreateRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedLobbyLobbyIdRoute: AuthedLobbyLobbyIdRoute,
  AuthedLobbyCreateRoute: AuthedLobbyCreateRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RulesRoute: RulesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
